apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mutating-webhook
spec:
  targetNamespace: mutating-webhook-prod
  values:
    replicaCount: 3
    image:
      tag: prod-latest
    webhook:
      failurePolicy: Fail
      namespaceSelector:
        matchLabels:
          env: prod
