apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mutating-webhook
spec:
  targetNamespace: mutating-webhook-dev
  values:
    replicaCount: 1
    image:
      tag: dev-latest
    webhook:
      namespaceSelector:
        matchLabels:
          env: dev
