apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mutating-webhook
spec:
  targetNamespace: mutating-webhook-stage
  values:
    replicaCount: 2
    image:
      tag: stage-latest
    webhook:
      namespaceSelector:
        matchLabels:
          env: stage
